### ISSUE TITLE
How to install git

### ISSUE THREAD

**Issue by Anuragtech02** [IET-DAVV/website-client#29]

**Comment by manasbhandari** [comment]
Git for Mac Installer

1.Download the latest [Git for Mac installer](https://sourceforge.net/projects/git-osx-installer/files/).
2.Follow the prompts to install Git.
3.Open a terminal and verify the installation was successful by typing git --version:

4.Configure your Git username and email using the following commands, replacing Emma's name with your own. These details will be associated with any commits that you create:
<img width="567" alt="Screenshot 2022-11-24 at 6 56 44 PM" src="https://user-images.githubusercontent.com/107706027/203795600-e324ebfd-68bf-4764-b712-e50e68a30fe5.png">

5.(Optional) To make Git remember your username and password when working with HTTPS repositories, [configure the git-credential-osxkeychain helper](https://www.atlassian.com/git/tutorials/install-git#install-the-git-credential-osx).

Install Git on Linux

1.From your shell, install Git using apt-get:$ sudo apt-get update
$ sudo apt-get install git
2.Verify the installation was successful by typing git --version:
3. Configure your Git username and email using the following commands, replacing Emma's nam
<img width="555" alt="Screenshot 2022-11-24 at 7 03 30 PM" src="https://user-images.githubusercontent.com/107706027/203796907-eb17d34e-f5a0-4053-b2b3-90dc9b303881.png">
e with your own. These details will be associated with any commits that you create:

Install Git on Windows

1.Download the latest [Git for Windows installer](https://git-for-windows.github.io/).
2.When you've successfully started the installer, you should see the Git Setup wizard screen. Follow the Next and Finish prompts to complete the installation. The default options are pretty sensible for most users.
3.Open a Command Prompt (or Git Bash if during installation you elected not to use Git from the Windows Command Prompt).
4.Run the following commands to configure your Git username and email using the following commands, replacing Emma's name with your own. These details will be associated with any commits that you create:
<img width="536" alt="Screenshot 2022-11-24 at 7 06 32 PM" src="https://user-images.githubusercontent.com/107706027/203797451-cb3e3044-cc01-4b88-be01-adb42fff5d8b.png">
5.Optional: Install the Git credential helper on Windows

Bitbucket supports pushing and pulling over HTTP to your remote Git repositories on Bitbucket. Every time you interact with the remote repository, you must supply a username/password combination. You can store these credentials, instead of supplying the combination every time, with the [Git Credential Manager for Windows](https://github.com/GitCredentialManager/git-credential-manager).
